// <auto-generated />
using System;
using EdPay.RechargeApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdPay.RechargeApp.Infrastructure.Migrations
{
    [DbContext(typeof(RechargeAppDBContext))]
    [Migration("20240517154920_initialDatabaseCreation")]
    partial class initialDatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EdPay.RechargeApp.Domain.Models.Beneficiary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BeneficiaryID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("EdPay.RechargeApp.Domain.Models.CreditRule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AmountLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PerBeneficiary")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("CreditRules");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AmountLimit = 1000m,
                            Description = "NonVerifiedUser",
                            PerBeneficiary = true
                        },
                        new
                        {
                            ID = 2,
                            AmountLimit = 500m,
                            Description = "VerifiedUser",
                            PerBeneficiary = true
                        },
                        new
                        {
                            ID = 3,
                            AmountLimit = 3000m,
                            Description = "VerifiedUserPerMonth",
                            PerBeneficiary = false
                        });
                });

            modelBuilder.Entity("EdPay.RechargeApp.Domain.Models.RechargeHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BeneficiaryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("RechargeHistory");
                });

            modelBuilder.Entity("EdPay.RechargeApp.Domain.Models.TopupPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TopupPlans");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 5,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 5"
                        },
                        new
                        {
                            ID = 2,
                            Amount = 10,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 10"
                        },
                        new
                        {
                            ID = 3,
                            Amount = 20,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 20"
                        },
                        new
                        {
                            ID = 4,
                            Amount = 30,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 30"
                        },
                        new
                        {
                            ID = 5,
                            Amount = 50,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 50"
                        },
                        new
                        {
                            ID = 6,
                            Amount = 75,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 75"
                        },
                        new
                        {
                            ID = 7,
                            Amount = 100,
                            Currency = "AED",
                            IsActive = true,
                            PlanDescription = "AED 100"
                        });
                });

            modelBuilder.Entity("EdPay.RechargeApp.Domain.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
